#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/wayfire"
RASI="$DIR/theme/rofi/launcher.rasi"

# Run
rofi \
    -show drun \
	-kb-cancel Super_L \
	-theme ${RASI}
